services:
  db:
    image: postgres:16
    container_name: app-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: backenduser
      POSTGRES_PASSWORD: mypassword # <-- change to a secure password for actual production environments
      POSTGRES_DB: mosaicdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backenduser -d mosaicdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: photo-mosaic-backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - mosaic-data:/app/storage
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=mosaicdb;Username=backenduser;Password=mypassword"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: photo-mosaic-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  
  redis:
    image: redis:8
    container_name: redis

  python-api:
    build:
      context: ./processing
      dockerfile: Dockerfile
    container_name: python-api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_CALLBACK_URL=http://backend:8080/jobs
    depends_on:
      - redis

  worker:
    build:
      context: ./processing
      dockerfile: Dockerfile
    command: rq worker --url redis://redis:6379 default
    environment:
      - BASE_PATH=/app/storage/images
      - BACKEND_CALLBACK_URL=http://backend:8080/jobs
    depends_on:
      - redis
    volumes:
      - mosaic-data:/app/storage

volumes:
  postgres_data:
  mosaic-data:
